package com.redhat.vizuri.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PushNotification implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "message")
   private java.lang.String message;
   @org.kie.api.definition.type.Label(value = "sound")
   private java.lang.String sound;

   public PushNotification()
   {
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public java.lang.String getSound()
   {
      return this.sound;
   }

   public void setSound(java.lang.String sound)
   {
      this.sound = sound;
   }

   public PushNotification(java.lang.String message, java.lang.String sound)
   {
      this.message = message;
      this.sound = sound;
   }
   
   @Override
   public String toString() {
       return "{\"message\" : \"" + message + "\", \"sound\" : \"" + sound + "\"}";
   }

}